version: 1.0.{build}

image: Visual Studio 2019

shallow_clone: true
clone_depth: 1

configuration:
  - Release-Far3

platform:
  - Win32
  - x64

build:
  project: src\Observer.sln
  verbosity: minimal

test: off

matrix:
  fast_finish: true

install:
  - SET PATH=%PATH%;C:\msys64\usr\bin
  - cd src\extra
  - m4 -P version.m4 > version.txt
  - SET /p PVER=<version.txt
  - appveyor UpdateBuild -Version %PVER%.%APPVEYOR_BUILD_NUMBER%
  - DEL version.txt
  - IF "%platform%" == "Win32" (SET P_ARCH=x86) ELSE (SET P_ARCH=%platform%)
  - cd C:\Tools\vcpkg
  - git pull --prune --quiet
  - .\bootstrap-vcpkg.bat -disableMetrics
  - vcpkg integrate install
  - vcpkg install zlib:%P_ARCH%-windows
  - vcpkg install bzip2:%P_ARCH%-windows
  - vcpkg install glib:%P_ARCH%-windows
  - vcpkg install libmspack:%P_ARCH%-windows
  - vcpkg install gmime:%P_ARCH%-windows
  - vcpkg install boost-iostreams:%P_ARCH%-windows
  - cd %APPVEYOR_BUILD_FOLDER%

cache:
  - c:\tools\vcpkg\installed\ -> appveyor.yml

after_build:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%

    xcopy bin\%configuration%-%platform%\* export\Observer /E /I /Y > nul

    7z a -r -sdel -bd -x!*.ipdb -x!*.iobj -x!*.metagen -- Observer_%configuration:~-4%_%P_ARCH%_%PVER%.7z .\export\*

artifacts:
  - path: '*.7z'
    name: distr

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: $(PVER)
    description: 'Stable Release'
    auth_token:
      secure: WzhK82JwGPRgmA9SP/CGMdsBKPjZD1oBAYl9IxKTlCBGJjJ7Txco20uCX52IfeQx
    artifact: distr
    draft: true
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true        # deploy on tag push only
